language: python
dist: xenial

python:
  - "3.9"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="ILMO.settings"
    - PYTHONPATH="/home/travis/build/moan0s/ILMO"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.7 DB=mysql

#commands to install dependencies
install:
  - working-directory: ./src
  - pip install -q Django==$DJANGO
  - pip install -q -r ´requirements.txt

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - working-directory: ./src
  - python manage.py test
